### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by erelsgl**
This pull request contains two types of additions:

* In existing code: added documentation, doctests, and some auxiliary functions.
* New code: added module to check for level-1-consensus --- a new domain-restriction by Mahajne et al, (2015). Added experiments to test the probability of this restriction in both PrefLib and randomly-generated profiles.

### CODE REVIEW

**Comment by AforAnonymous** [comment]
May I suggest updating this pull request so it's based on a new branch of your master branch, since it had additional development, like so:
https://github.com/nmattei/PrefLib-Tools/compare/develop...erelsgl:master

...except with a different README.MD obviously, otherwise you'd make it look like this project forked itself.

**Comment by erelsgl** [comment]
@AforAnonymous  done

**Comment by AforAnonymous** [comment]
Cool! I hope @nmattei picks up on it :)

**Comment by nmattei** [comment]
Ah, sorry guys, somehow this flew under my radar...!

**Comment by nmattei** [comment]
@AforAnonymous and @erelsgl thanks for the updates -- I really need to get back to working on this a bit more but it's hard to find the time these days... maybe after AAAI ;-)

**Pull request merged**
